---
name: CI
on: [push]
jobs:
  skipci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "[ci skip] ${{ contains(github.event.head_commit.message, '[ci skip]') }}"
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install tools
      run: bash ci/install-tools.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: update pr
      run: bash ci/update-pr.sh
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - name: merge master
      run: bash ci/merge-master.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: hello
      run: bash ci/hello.sh
